### ISSUE TITLE
Guys, what do you think about create TesselDrone.io?

### ISSUE THREAD

**Issue by jdnichollsc** [ConnectedMachines/TesselDrone#70]
Hi guys,

I bought **Tessel 2** kit and I want to create a drone using **Node.js**

Do you want this project to be community?

Regards, Nicholls

**Comment by mLuby** [comment]
@jdnichollsc sure, we're open to that!

We should inform you that we ran into flight-crippling timing delays, so our quadcopter was not capable of hovering flight.
It was taking ~200ms to do a full feedback cycle between:
-> `attitude sensor output`
-> `flight program's PID controller`
-> `servo controller`
-> `motor speed change`
-> `orientation change`
which is far too much delay to keep a quadcopter stable.

Also we only used an accelerometer, which was not accurate enough about the orientation of the drone.

If you are intent on creating a drone with a Tessel, I strongly suggest you buy a flight controller chip that combines IMU and PID, then use the Tessel to issue higher-level commands like "go left", rather than trying to build the flight control software itself in JS.

**Comment by jdnichollsc** [comment]
Excellent! Thanks @mLuby for the quickly response and your comments!

What do you think about Tessel 2? **_Maybe it should work better on Tessel 2..._**

And what **_controller chip that combines IMU and PID_** do you recommend?

Regards, Nicholls

**Comment by mLuby** [comment]
🙂 I doubt the difference between Tessel 1 and 2 makes a difference, but I could be wrong.

Can't find the research we did on IMU/PID chips (AKA flight computers?), but these may point you in the right direction:
- http://www.scoutuav.com/2011/12/13/low-cost-arduino-based-auto-stabilizing-system/
- http://www.robotshop.com/blog/en/how-to-make-a-drone-uav-lesson-4-flight-controller-15191

**Comment by jdnichollsc** [comment]
Excellent, thanks my friend! For example a [CC3D flight controller](https://www.amazon.com/s/ref=nb_sb_ss_i_1_7?url=search-alias%3Dtoys-and-games&field-keywords=cc3d+flight+controller&sprefix=cc3d+fl%2Ctoys-and-games%2C205&crid=2DAE074AMDJNM)
Guys, check the tessel slack group [here](https://tessel-slack.herokuapp.com/)

And what's your code of the Fligth Control in **Node.js**? (It's only to see haha) :)

Regards, Nicholls

**Comment by mLuby** [comment]
See [this file](https://github.com/ConnectedMachines/TesselDrone/blob/dev/tessel/server-fly) (and the [tessel directory](https://github.com/ConnectedMachines/TesselDrone/tree/dev/tessel)).

**Comment by mLuby** [comment]
Closing as old and no action necessary.
